### ISSUE TITLE
Complete bioconductor submission & review

### ISSUE THREAD

**Issue by joreynajr** [Muunraker/nipalsMCIA#27]

**Comment by akonstodata** [comment]
@joreynajr @Muunraker @eba28 

Current results of devtools::check() as of 11/6/, 9am EST
Note that only Vignette 1 Rmd file was kept in vignettes/ folder for checking

Please review, especially comments that pertain to code and/or data that you are the lead on.

── R CMD check results ─────────────────────────────────────────────────────────────────────────────────────────────────── nipalsMCIA 0.1.0 ────
Duration: 1m 24.3s

❯ checking examples ... ERROR
  Running examples in ‘nipalsMCIA-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: CCpreproc
  > ### Title: Centered Column Profile Pre-processing
  > ### Aliases: CCpreproc
  > 
  > ### ** Examples
  > 
  > preproced_df <- CCpreproc(df)
  Error in as.vector(x, mode) : 
    cannot coerce type 'closure' to vector of type 'any'
  Calls: CCpreproc ... as.matrix -> as.matrix.default -> array -> as.vector
  Execution halted

❯ checking package subdirectories ... WARNING
  Invalid citation information in ‘inst/CITATION’:
    Error in parse(con): 2:5: unexpected symbol
    1: nipalsMCIA
    2: Max Mattessich
           ^

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'gsea_report'
    ‘factors’ ‘nproc’
  Documented arguments not in \usage in documentation object 'gsea_report':
    ‘factor’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking contents of ‘data’ directory ... WARNING
  Files not of a type allowed in a ‘data’ directory:
    ‘c2.cp.reactome.v6.2.symbols.gmt’ ‘data_blocks_sc.Rda’
  Please use e.g. ‘inst/extdata’ for non-R data files

❯ checking data for ASCII and uncompressed saves ... WARNING
    
    Note: significantly better compression could be obtained
          by using R CMD build --resave-data
              old_size new_size compress
    NCI60.rda    1.2Mb    931Kb       xz

❯ checking for portable file names ... NOTE
  Found the following non-portable file paths:
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part0.Introduction.Rmd
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part1.Item1.2D-Plots-and-Scree.OLD.Rmd
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part1.Item1.2D-Plots-and-Scree.Rmd
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part1.Item2.Heatmap.Rmd
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part2.Item1.Pseudoeigenvalues.Rmd
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part2.Item2.Scree.Rmd
    nipalsMCIA/vignettes/archived/Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part2.Item3.Pathway-Analysis.Rmd
  
  Tarballs are only required to store paths of up to 100 bytes and cannot
  store those of more than 256 bytes, with restrictions including to 100
  bytes for the final component.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.

❯ checking installed package size ... NOTE
    installed size is 25.8Mb
    sub-directories of 1Mb or more:
      data  20.3Mb
      doc    5.3Mb

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘biocCheck.txt’

❯ checking R code for possible problems ... NOTE
  vis_load_ord: warning in factor(omic_name, level = omic_name): partial
    argument match of 'level' to 'levels'
  NIPALS_iter : <anonymous>: no visible global function definition for
    ‘var’
  NIPALS_iter : <anonymous>: no visible global function definition for
    ‘cov’
  block_weights_heatmap: no visible global function definition for
    ‘heatmap’
  global_scores_eigenvalues_plot: no visible global function definition
    for ‘barplot’
  global_scores_heatmap: no visible binding for global variable
    ‘mcia_results’
  gsea_report: no visible global function definition for ‘setNames’
  gsea_report: no visible global function definition for ‘n_distinct’
  nipals_multiblock: no visible global function definition for ‘par’
  projection_plot : <anonymous>: no visible global function definition
    for ‘var’
  projection_plot: no visible global function definition for ‘grid’
  projection_plot: no visible global function definition for ‘points’
  projection_plot: no visible global function definition for ‘segments’
  projection_plot: no visible global function definition for ‘legend’
  vis_load_ord: no visible binding for global variable ‘omic_name’
  vis_load_ord: no visible binding for global variable ‘loading’
  vis_load_ord: no visible binding for global variable ‘omic’
  vis_load_ord: no visible global function definition for ‘element_text’
  Undefined global functions or variables:
    barplot cov element_text grid heatmap legend loading mcia_results
    n_distinct omic omic_name par points segments setNames var
  Consider adding
    importFrom("graphics", "barplot", "grid", "legend", "par", "points",
               "segments")
    importFrom("stats", "cov", "heatmap", "setNames", "var")
  to your NAMESPACE file.

❯ checking for unstated dependencies in vignettes ... NOTE
  'library' or 'require' call not declared from: ‘stringr’

1 error ✖ | 4 warnings ✖ | 5 notes ✖
